Remove remaining instances of "rate tick" from RFQ systems
lightninglabs/taproot-assets pull request #1156
Opened 2024-10-21 16:32 UTC by ffranr

Depends on https://github.com/lightninglabs/taproot-assets/pull/1155 which should be merged first. This PR is in draft until then.

This PR removes any remaining mention of "rate tick" from the Price Oracle RPC endpoints and the RFQ packages.

2024-10-21 16:36 UTC, ffranr commented
The remaining RFQ cleanup work after this PR is merge:

* Add request message fields: `suggestedOutAssetRate` and `transferType`.
* Rearrange fields in request message to correspond with BLIP (refactor only, no logic changes, TLV values should be correct after current PR is merged).

2024-10-21 19:04 UTC, dstadulis requested changes

2024-10-21 19:07 UTC, ffranr commented on docs/examples/basic-price-oracle/main.go
> +// Alice requests a bid quote from Bob. Her request includes an asset rates hint
The request includes an in-asset to BTC rate hint and an out-asset to BTC rate hint.

2024-10-21 19:08 UTC, ffranr commented on docs/examples/basic-price-oracle/main.go
> +// (ask). Alice get the asset rates hint by calling this endpoint. She sets:
I've gone with "Alice obtains". Let me know if you think "receives" is better or something else.

2024-10-21 19:15 UTC, ffranr commented on taprpc/priceoraclerpc/price_oracle.swagger.json
> +          "description": "paymentAssetRate is the number of payment asset units per BTC represented\nas a fixed-point number. This field is also commonly referred to as the\npayment asset to BTC (con
I've gone with:
```
When the payment asset is BTC,
    // this field should be set to 100 billion, as one BTC is equivalent to 100
    // billion msats.
```

2024-10-21 19:18 UTC, ffranr commented on taprpc/priceoraclerpc/price_oracle.swagger.json
> +      "description": "QueryAssetRatesErrResponse is the error response to a QueryAssetRates call."
`QueryAssetRatesErrResponse` encapsulates all error responses from a price oracle service `QueryAssetRates` endpoint call.

2024-10-21 19:23 UTC, ffranr commented on taprpc/priceoraclerpc/price_oracle.pb.go
> +func (*QueryAssetRatesResponse) Descriptor() ([]byte, []int) {
This was auto-generated by our protos generator. It's probably in place for backwards compatibility. I think we can ignore this.

2024-10-22 08:08 UTC, dstadulis commented on docs/examples/basic-price-oracle/main.go
> +// (ask). Alice get the asset rates hint by calling this endpoint. She sets:
obtains sgtm

2024-10-22 08:46 UTC, merged